server:
  port: 8086
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/chinalife
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.43.178
    username: chinalife
    password: cl123
    virtual-host: /chinalife
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
