server:
  port: 10001
spring:
  application:
    name: cl-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
    fetch-registry: true         #不拉取服务列表
    register-with-eureka: false
